[build-system]
requires = ["uv_build>=0.11.6,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "dijkstar"

[project]
name = "Dijkstar"
version = "3.0a7.dev0"
description = "Dijkstra/A*"
authors = [{ name = "Wyatt Baldwin", email = "code@wyattbaldwin.com" }]
readme = "README.md"
license = "MIT"
repository = "https://github.com/wylee/Dijkstar"
keywords = ["Dijkstra", "A*", "graph", "algorithm", "shortest paths"]

requires-python = ">=3.11"

dependencies = [
    "runcommands>=1.0a73",
    # Client & Server
    "python-multipart>=0.0.28",
    "requests>=2.33.1",
]

[dependency-groups]
dev = [
    "com.wyattbaldwin.make-release",
    "coverage",
    "ruff",
    "tox",
]

[project.optional-dependencies]
server = [
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
    "starlette>=1.0.0",
    "uvicorn>=0.46.0",
]

[project.scripts]
dijkstar = "dijkstar.__main__:main.console_script"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
